services:
  - type: web
    name: product-recommendation-system
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
